stages:
  prepare-bad:
    cmd: uv run --package prepare -- python -m prepare.__main__ run-workflow data/raw/bad data/prepared
    deps:
      - apps/prepare/src/prepare
      - data/raw/bad
    outs:
      - data/prepared/lower_body/bad
      - data/prepared/upper_body/bad

  prepare-good:
    cmd: uv run --package prepare -- python -m prepare.__main__ run-workflow data/raw/good data/prepared
    deps:
      - apps/prepare/src/prepare
      - data/raw/good
    outs:
      - data/prepared/lower_body/good
      - data/prepared/upper_body/good

  featurize-lower-body:
    cmd: uv run --package featurize -- python -m featurize.__main__ data/prepared/lower_body data/features
    deps:
      - apps/featurize/src/featurize
      - data/prepared/lower_body
    outs:
      - data/features/lower_body

  train-lower-body:
    cmd: uv run --package train -- python -m train.train data/features/lower_body models/model_lower_body.pkl metrics_train_lower_body.json
    deps:
      - apps/train/src/train
      - data/features/lower_body
    outs:
      - models/model_lower_body.pkl
    metrics:
      - metrics_train_lower_body.json

  evaluate-lower-body:
    cmd: uv run --package evaluate -- python -m evaluate.main models/model.pkl data/test metrics_.json
    deps:
      - apps/evaluate/src/evaluate
      - models/model_lower_body.pkl
      - data/test
    metrics:
      - metrics_eval_lower_body.json

params:
    - params.yaml

# TODO: specify artifact used by the project, 
# example from https://dvc.org/doc/user-guide/project-structure/dvcyaml-files :
# artifacts:
#   cv-classification: # artifact ID (name )
#     path: models/resnet.pt
#     type: model
#     desc: 'CV classification model, ResNet50'
#     labels:
#       - resnet50
#       - classification
#     meta:
#       framework: pytorch
