stages:
  prepare:
    cmd: uv run --package prepare -- python -m prepare.__main__ run-workflow data/raw data/prepared
    deps:
      - apps/prepare/src/prepare
    outs:
      - data/prepared

  featurize:
    cmd: uv run --package featurize -- python -m featurize.__main__ data/prepared data/features
    deps:
      - apps/featurize/src/featurize
      - data/prepared
    outs:
      - data/features

  train:
    cmd: uv run --package train -- python -m train.train data/features models/model.pkl metrics.json
    deps:
      - apps/train/src/train
      - data/features
    outs:
      - models/model.pkl
    metrics:
      - metrics_train.json

  evaluate:
    cmd: uv run --package evaluate -- python -m evaluate.main models/model.pkl data/test metrics.json
    deps:
      - apps/evaluate/src/evaluate
      - models/model.pkl
      - data/test
    metrics:
      - metrics_eval.json

params:
    - params.yaml

# TODO: specify artifact used by the project, 
# example from https://dvc.org/doc/user-guide/project-structure/dvcyaml-files :
# artifacts:
#   cv-classification: # artifact ID (name )
#     path: models/resnet.pt
#     type: model
#     desc: 'CV classification model, ResNet50'
#     labels:
#       - resnet50
#       - classification
#     meta:
#       framework: pytorch
